//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.23 at 03:33:57 PM EDT 
//


package models;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SurveyDefinition }
     * 
     */
    public SurveyDefinition createSurveyDefinition() {
        return new SurveyDefinition();
    }

    /**
     * Create an instance of {@link SurveyDefinition.EmbeddedData }
     * 
     */
    public SurveyDefinition.EmbeddedData createSurveyDefinitionEmbeddedData() {
        return new SurveyDefinition.EmbeddedData();
    }

    /**
     * Create an instance of {@link SurveyDefinition.SurveyFlow }
     * 
     */
    public SurveyDefinition.SurveyFlow createSurveyDefinitionSurveyFlow() {
        return new SurveyDefinition.SurveyFlow();
    }

    /**
     * Create an instance of {@link SurveyDefinition.Blocks }
     * 
     */
    public SurveyDefinition.Blocks createSurveyDefinitionBlocks() {
        return new SurveyDefinition.Blocks();
    }

    /**
     * Create an instance of {@link SurveyDefinition.Blocks.Block }
     * 
     */
    public SurveyDefinition.Blocks.Block createSurveyDefinitionBlocksBlock() {
        return new SurveyDefinition.Blocks.Block();
    }

    /**
     * Create an instance of {@link SurveyDefinition.Blocks.Block.BlockElements }
     * 
     */
    public SurveyDefinition.Blocks.Block.BlockElements createSurveyDefinitionBlocksBlockBlockElements() {
        return new SurveyDefinition.Blocks.Block.BlockElements();
    }

    /**
     * Create an instance of {@link SurveyDefinition.Questions }
     * 
     */
    public SurveyDefinition.Questions createSurveyDefinitionQuestions() {
        return new SurveyDefinition.Questions();
    }

    /**
     * Create an instance of {@link SurveyDefinition.Questions.Question }
     * 
     */
    public SurveyDefinition.Questions.Question createSurveyDefinitionQuestionsQuestion() {
        return new SurveyDefinition.Questions.Question();
    }

    /**
     * Create an instance of {@link SurveyDefinition.Questions.Question.Choices }
     * 
     */
    public SurveyDefinition.Questions.Question.Choices createSurveyDefinitionQuestionsQuestionChoices() {
        return new SurveyDefinition.Questions.Question.Choices();
    }

    /**
     * Create an instance of {@link SurveyDefinition.Languages }
     * 
     */
    public SurveyDefinition.Languages createSurveyDefinitionLanguages() {
        return new SurveyDefinition.Languages();
    }

    /**
     * Create an instance of {@link SurveyDefinition.EmbeddedData.Field }
     * 
     */
    public SurveyDefinition.EmbeddedData.Field createSurveyDefinitionEmbeddedDataField() {
        return new SurveyDefinition.EmbeddedData.Field();
    }

    /**
     * Create an instance of {@link SurveyDefinition.SurveyFlow.EmbeddedData }
     * 
     */
    public SurveyDefinition.SurveyFlow.EmbeddedData createSurveyDefinitionSurveyFlowEmbeddedData() {
        return new SurveyDefinition.SurveyFlow.EmbeddedData();
    }

    /**
     * Create an instance of {@link SurveyDefinition.SurveyFlow.Block }
     * 
     */
    public SurveyDefinition.SurveyFlow.Block createSurveyDefinitionSurveyFlowBlock() {
        return new SurveyDefinition.SurveyFlow.Block();
    }

    /**
     * Create an instance of {@link SurveyDefinition.Blocks.Block.BlockElements.Question }
     * 
     */
    public SurveyDefinition.Blocks.Block.BlockElements.Question createSurveyDefinitionBlocksBlockBlockElementsQuestion() {
        return new SurveyDefinition.Blocks.Block.BlockElements.Question();
    }

    /**
     * Create an instance of {@link SurveyDefinition.Questions.Question.Validation }
     * 
     */
    public SurveyDefinition.Questions.Question.Validation createSurveyDefinitionQuestionsQuestionValidation() {
        return new SurveyDefinition.Questions.Question.Validation();
    }

    /**
     * Create an instance of {@link SurveyDefinition.Questions.Question.Choices.Choice }
     * 
     */
    public SurveyDefinition.Questions.Question.Choices.Choice createSurveyDefinitionQuestionsQuestionChoicesChoice() {
        return new SurveyDefinition.Questions.Question.Choices.Choice();
    }

    /**
     * Create an instance of {@link SurveyDefinition.Languages.Language }
     * 
     */
    public SurveyDefinition.Languages.Language createSurveyDefinitionLanguagesLanguage() {
        return new SurveyDefinition.Languages.Language();
    }

}
